apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fake.fullname" . }}-httpd
  labels:
    {{- include "fake.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-httpd
  template:
    metadata:
      labels:
        app: fake-httpd
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "80"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: fake-httpd
        image: python:3.13.10-alpine3.22
        command: ["python3","-u","/srv/httpd.py"]
        volumeMounts:
          - name: srv-vol
            mountPath: /srv
        ports:
        - containerPort: 80
      volumes:
        - name: srv-vol
          configMap:
            name: {{ include "fake.fullname" . }}-cfg1
            items:
              - key: httpd_py
                path: httpd.py
