{{- if ( .Values.httpd_enabled | default false ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fake.fullname" . }}
  labels:
    {{- include "fake.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "fake.selectorLabels" . | nindent 4 }}
{{- end }}
