env:
  dev:
    ssh_authorized_keys:
    - "ssh-rsa DEV..."
    targets:
    - 192.168.2.101
    - 192.168.2.102
    - 192.168.2.103
  prod:
    ssh_authorized_keys:
    - "ssh-rsa PROD..."
    targets:
    - 192.168.2.111
