env:
  dev:
    ssh_authorized_keys:
    - "ssh-rsa DEV..."
    targets:
    - 192.168.56.51
    - 192.168.56.52
    - 192.168.56.53
    k3s: off
    k3s_token: "b92f2f94-8b58-40c2-a876-06555179b48e"
  prod:
    ssh_authorized_keys:
    - "ssh-rsa PROD..."
    targets:
    - 192.168.56.51
    k3s: off
    k3s_token: "aade443b-8628-49b8-aff3-fd5e1390b331"
