apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis
data:
  init-py: |
    {{- .Files.Get "app/__init__.py" | nindent 4 }}
  main-py: |
    {{- .Files.Get "app/__main__.py" | nindent 4 }}
  install-py: |
    {{- .Files.Get "app/install.py" | nindent 4 }}
