apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis
data:
  init-py: |
    {{- include "__init__.py" . | nindent 4 }}
  main-py: |
    {{- include "__main__.py" . | nindent 4 }}
  install-py: |
    {{- include "install.py" . | nindent 4 }}
