apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genesis.fullname" . }}
  labels:
    {{- include "genesis.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "genesis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "genesis.labels" . | nindent 8 }}
    spec:
      hostPID: true
      serviceAccountName: genesis-account
      terminationGracePeriodSeconds: 5
      containers:
      - name: {{ .Chart.Name }}
        image: ghcr.io/sfmunoz/k8s-bulk:v1.6.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        # enforce code changes -> container restarted (devel environment)
        - name: PYTHONPATH
          value: /app
        - name: CODE_SHA256SUM
          value: {{ include "genesis.code_sha256sum" . | quote }}
        - name: VALUES_PEERING_NAME
          value: {{ .Values.peering_name | quote }}
        command: ["python3","-m","genesis"]
        volumeMounts:
        - mountPath: /genesis
          name: vol-host
          readOnly: false
        - mountPath: /app
          name: app-vol
        - mountPath: /sec
          name: secret-vol
      volumes:
      - name: vol-host
        hostPath:
          path: /
          type: Directory
      - name: app-vol
        configMap:
          name: genesis
          items:
          - key: init-py
            path: genesis/__init__.py
          - key: main-py
            path: genesis/__main__.py
          - key: butane-py
            path: genesis/butane.py
          - key: install-py
            path: genesis/install.py
          - key: flatcar-update-conf
            path: genesis/templates/flatcar-update.conf
          - key: flatcar-yaml
            path: genesis/templates/flatcar.yaml
      - name: secret-vol
        secret:
          secretName: genesis
