apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genesis.fullname" . }}
  labels:
    {{- include "genesis.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "genesis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "genesis.labels" . | nindent 8 }}
    spec:
      hostPID: true
      serviceAccountName: genesis-account
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}
        image: ghcr.io/sfmunoz/k8s-bulk:v1.3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        # enforce code changes -> container restarted (devel environment)
        - name: PYTHONPATH
          value: /app
        - name: CODE_SHA256SUM
          value: "{{ include "__init__.py" . | sha256sum }}_{{ include "__main__.py" . | sha256sum }}"
        command: ["python3","-m","genesis"]
        volumeMounts:
        - mountPath: /genesis
          name: vol-host
          readOnly: false
        - mountPath: /app
          name: app-vol
      volumes:
      - name: vol-host
        hostPath:
          path: /
          type: Directory
      - name: app-vol
        configMap:
          name: genesis
          items:
          - key: init-py
            path: genesis/__init__.py
          - key: main-py
            path: genesis/__main__.py
